### ISSUE TITLE
Adding PositionEventFinder calculation type ?

### ISSUE THREAD

**Issue by BaptisteCecconi** [seignovert/python-webgeocalc#3]
Hi @seignovert, do you have any plan to include the `PositionEventFinder` calculation type?

**Comment by BaptisteCecconi** [comment]
Does `GF_COORDINATE_SEARCH` correspond to `PositionEventFinder`? 

If so, it would be nice to have a lookup table to map the API methods with the web interface feature names.

**Comment by jdiazdelrio** [comment]
Hi @BaptisteCecconi,

yes, `GF_COORDINATE_SEARCH` corresponds to **Position Event Finder** in the WGC web interface. All other features match if you take into consideration that the prefix `GF_` indicates "Event Finder" capability. Note that **Target in Field of View Event Finder** corresponds to `GF_TARGET_IN_INSTRUMENT_FOV_SEARCH`.

**Comment by BaptisteCecconi** [comment]
Thanks @jdiazdelrio 
I'll see what I can do with this. I may propose a pull request implementing `GF_COORDINATE_SEARCH` if you agree.

**Comment by seignovert** [comment]
Hi @BaptisteCecconi,
You are right I did not implement de `GF_*` entry points yet, but I will be happy to add your PR.

Just for reference, here is the full list of the missing entries, as described [in the docs](https://wgc2.jpl.nasa.gov:8443/webgeocalc/documents/api-info.html):

| Web interface | API | Implementation |
|---------------|-----|:--------------:|
| [Position Finder](http://spice.esac.esa.int/webgeocalc/#CoordinateFinder)                  | [`GF_COORDINATE_SEARCH`](https://wgc2.jpl.nasa.gov:8443/webgeocalc/documents/api-info.html#GF_COORDINATE_SEARCH)                             | #4 |
| [Angular Separation Finder](http://spice.esac.esa.int/webgeocalc/#AngularSeparationFinder) | [`GF_ANGULAR_SEPARATION_SEARCH`](https://wgc2.jpl.nasa.gov:8443/webgeocalc/documents/api-info.html#GF_ANGULAR_SEPARATION_SEARCH)             |    |
| [Distance Finder](http://spice.esac.esa.int/webgeocalc/#DistanceFinder)                    | [`GF_DISTANCE_SEARCH`](https://wgc2.jpl.nasa.gov:8443/webgeocalc/documents/api-info.html#GF_DISTANCE_SEARCH)                                 |    |
| [Sub-Point Finder](http://spice.esac.esa.int/webgeocalc/#SubPointFinder)                   | [`GF_SUB_POINT_SEARCH`](https://wgc2.jpl.nasa.gov:8443/webgeocalc/documents/api-info.html#GF_SUB_POINT_SEARCH)                               |    |
| [Occultation Finder](http://spice.esac.esa.int/webgeocalc/#OccultationFinder)              | [`GF_OCCULTATION_SEARCH`](https://wgc2.jpl.nasa.gov:8443/webgeocalc/documents/api-info.html#GF_OCCULTATION_SEARCH)                           |    |
| [Surface Intercept Finder](http://spice.esac.esa.int/webgeocalc/#SurfaceInterceptFinder)   | [`GF_SURFACE_INTERCEPT_POINT_SEARCH`](https://wgc2.jpl.nasa.gov:8443/webgeocalc/documents/api-info.html#GF_SURFACE_INTERCEPT_POINT_SEARCH)   |    |
| [Target in Field of View Finder](http://spice.esac.esa.int/webgeocalc/#TargetInFOVFinder)  | [`GF_TARGET_IN_INSTRUMENT_FOV_SEARCH`](https://wgc2.jpl.nasa.gov:8443/webgeocalc/documents/api-info.html#GF_TARGET_IN_INSTRUMENT_FOV_SEARCH) |    |
| [Ray in Field of View Finder](http://spice.esac.esa.int/webgeocalc/#RayInFOVFinder)        | [`GF_RAY_IN_FOV_SEARCH`](https://wgc2.jpl.nasa.gov:8443/webgeocalc/documents/api-info.html#GF_RAY_IN_FOV_SEARCH)                             |    |
| [Range Rate Finder](http://spice.esac.esa.int/webgeocalc/#RangeRateFinder)                 | [`GF_RANGE_RATE_SEARCH`](https://wgc2.jpl.nasa.gov:8443/webgeocalc/documents/api-info.html#GF_RANGE_RATE_SEARCH)                             |    |
| [Phase Angle Finder](http://spice.esac.esa.int/webgeocalc/#PhaseAngleFinder)               | [`GF_PHASE_ANGLE_SEARCH`](https://wgc2.jpl.nasa.gov:8443/webgeocalc/documents/api-info.html#GF_PHASE_ANGLE_SEARCH)                           |    |

This should be include in the [module docs](https://webgeocalc.readthedocs.io/en/latest/calculation.html) as well.

It's open to debate, but I would recommend to use the Web naming convention (I find them more clear):
```python
from webgeocalc import PositionFinder
```
instead of
```python
from webgeocalc import GFCoordinateSearch
```

We can always overload `GFCoordinateSearch` as child of `PositionFinder` (or the other way around) but it might be confusion for the end-user.

I'm open to suggestions!

**Comment by seignovert** [comment]
Actually… I realized that I'm using `OsculatingElements` naming convention instead of `OrbitalElements`.

So you are right, it may be relevant to implement it as `GFCoordinateSearch` and eventually overload it as `PositionFinder` (to keep backward compatibility).
